### ISSUE TITLE
champ ha_server incorrect

### ISSUE THREAD

**Issue by hayvan96** [mdeweerd/MetersToHA#10]
Bonjour
J'ai installé metersToHA directement comme module complémentaire, et configuré le module par l'onglet correspondant.
J'ai beau mettre "http://homeassistant.local:8123" sur le champ "ha_server", lorsque je regarde le log à l'exécution du module, je constate : 

- que les login/mdp gazpar sont bien pris en compte
- en revanche, le ha:server affiché dans le log est mon token
- le token est un autre champ très long, mais qui n'est pas mon token rentré

de facto, le curl plante car il n'arrive pas à résoudre cette adresse qui n'est pas une URL.

j'ai retiré le 8123 pour voir si cela change quelque chose, mais j'ai l'impression que cela n'a aucun effet sur la (mauvaise) prise compte du champ du serveur lors de l'exécution du module.

merci pour votre aide !

**Comment by mdeweerd** [comment]
Je vais regarder cela.  Toutefois, ne mettez pas l'URL ni le token avec le Add-on quand c'est pour la même instance.
Le token et l'URL sont déterminés automatiquement.  L'URL sera http://supervisor.

Je dois corriger ce point, mais je ne l'ai pas vu car je ne l'ai pas testé comme cela.

Ce serait aussi à préciser plus clairement dans la descirption des champs + la doc.

**Comment by mdeweerd** [comment]
Cela devrait être réglé (nécessite de demander une mise à jour de l'add-on et une reconstruction ensuite).

**Comment by hayvan96** [comment]
Effectivement le module s'exécute correctement maintenant merci
