### ISSUE TITLE
Home assistant addon problème pce

### ISSUE THREAD

**Issue by dydydu10** [mdeweerd/MetersToHA#12]
Bonjour, 
Avec l'installation via l'addon, il y à un soucis avec les pce commençant par 0, home assistant retire de le 0 devant, ducoup le numéro n'est pas reconnu chez GRDF.  Il faudrait changé le champs par un str.

**Comment by mdeweerd** [comment]
Je ne peux faire plus vite ;-).  Redémarrez l'add-on et cela devrait être ok.

**Comment by hayvan96** [comment]
Depuis la mise à jour, l'addon ne démarre pas "not a valid value"

**Comment by mdeweerd** [comment]
@hayvan96 il faut le PCE sans espaces!
C'est peut-être là le problème.

**Comment by hayvan96** [comment]
Non, le problème était qu'il fallait totalement ré-écrire le PCE après la mise à jour ;)

**Comment by mdeweerd** [comment]
Apparemment il faut désormais des guillements dans la configuration YAML.
