### ISSUE TITLE
Pas d'ID sur les deux sensor créés.

### ISSUE THREAD

**Issue by Warp95** [mdeweerd/MetersToHA#21]
Bonjour,

Sans ID, impossible de les affecter a une pièce, ou de leur changer leur nom.

**Comment by mdeweerd** [comment]
Bonjour
J'ai du mettre HA à petite priorité.

Le données ne sont pas franchement remonté comme des "vraies entités" - je n'ai pas trouvé de bonne méthode pour faire cela - il y a probablement un moyen, mais quand j'ai travaillé dessus je n'ai pas trouvé comment créer des entités à travers l'API.

Du coup cela donne effectivmeent ceci:
![image](https://github.com/user-attachments/assets/6b033114-95e9-479f-a7dc-bb206467e797)

Une méthode est de créer une vraie entité sous HA, et de copier les valeurs qui arrivent dedans.

J'ai déjà passé pas mal de temps dessus dans le passé, donc je ne recreuse pas à nouveau.
S'il y a un exemple qqpart qui indique comment créer une vraie entité à travers l'API, je peux considérer une évolution.
