### ISSUE TITLE
[INFO] GRDF à encore changé l'accès

### ISSUE THREAD

**Issue by vingerha** [mdeweerd/MetersToHA#22]
Depuis qq jours GRDF n'a plus besoin d'un captcha et ils ont aussi changé la procedure. 
J'au pu arriver à adapter meters2ha.py mais c'est pas beau (je ne suis pas un dev)
Si qqu le veux tester...je pourrais le partager

**Comment by mdeweerd** [comment]
Ok, le code est-il disponible sur github?
Il est possible de faire un Pull Request, je peux regarder, tester, ajuster.

**Comment by vingerha** [comment]
Je vais tester qq jours et je te fait un PR mais attention...part de ce code vient de l'autre PR Release1 ... j'auste copié les truc pour GRDF car pas intéressé dans Véolia (ni la possibilité de le tester)
