### ISSUE TITLE
Erreur lors de la tentative de démarrage de l'outil via Docker

### ISSUE THREAD

**Issue by lambd1** [mdeweerd/MetersToHA#9]
Bonjour,

J'essaie de faire tourner le script avec la configuration suivante : 
* raspberry pi 4
* publication sur serveur mqtt
* pour home assistant
* via la commande docker
* en ayant bien suivi le readme pour créer le fichier de configuration

après le build de l'image docker et après quelques secondes, j'obtiens le message d'erreur suivant : 

```
MetersToHA $ docker compose run --rm meters-to-ha-grdf
Traceback (most recent call last):
  File "/workdir/./apps/meters_to_ha/meters_to_ha.py", line 3076, in doWork
    gazpar_file = crawler.get_gazpar_file()
  File "/workdir/./apps/meters_to_ha/meters_to_ha.py", line 1679, in get_gazpar_file
    content = self.__browser.find_element(By.TAG_NAME, "pre").text
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 738, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: headless chrome=112.0.5615.165); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workdir/./apps/meters_to_ha/meters_to_ha.py", line 3087, in doWork
    gazpar_file = crawler.get_gazpar_file()
  File "/workdir/./apps/meters_to_ha/meters_to_ha.py", line 1679, in get_gazpar_file
    content = self.__browser.find_element(By.TAG_NAME, "pre").text
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 738, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: headless chrome=112.0.5615.165); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

Pouvez-vous m'aider ? Est-ce que j'ai loupé quelque chose dans le readme ?

Je vous remercie,
cdt

**Comment by mdeweerd** [comment]
L'outil semble être arrivé à l'étape ou il est sensé avoir récupéré le fichier des données, et c'est sensé être présent sous un élément '<pre>...'.  Et c'est ce qu'il ne trouve pas.

De mon côté j'obtiens le même résultat...  Qqchse a peut-être changé ou c'est transitoire..

**Comment by mdeweerd** [comment]
Bon, j'ai le problème quand j'ai une configuration 'capmonster' pour lequel je n'ai pas de clef API.

Proceed with captcha resolution                                            ~~[EE] capmonster status 402{"errorId":1,"errorCode":"ERROR_ZERO_BALANCE","errorDescription":"Account has zero balance"}   

Ensuite cela donne cette erreur.

Sinon, ça fonctionne pour moi.

**Comment by mdeweerd** [comment]
Et pour info, cela fonctionne aussi avec 

```shell
docker compose run -eDISPLAY=10.33.2.69:0.0 --rm meters-to-ha-debug-grdf
```
et MobaXterm sans service: en attendant que le processus remplisse login et mdp.  Et puis faisant la résolution du captcha à la main suivi par un clic manuel sur "Connexion".

(j'ai du mettre mon IP directement car il y a un problème avec docker).

**Comment by lambd1** [comment]
merci pour votre retour. Je viens de voir l'ajout du support de captchaai; je vais essayer cette solution au lieu de capmonster (pour lequel je pensais avoir une période d'essai, mais peut être que non finalement); je suis en attente de l'activation de mon thread et de mon api key ;)
je vous tiens au courant si cela fonctionne.

merci et bonne soirée !

**Comment by mdeweerd** [comment]
Ah, j'étais surpris de voir le lien utilisé si vite !

Je suppose qu'il y avait quand même un message d'erreur à propos de capmonster dans ce cas.

Pour le moment j'ai principalement confirmé à captchaai que c'est en place de mon côté (et testé), j'attends confirmation de l'activation de l'offre...

**Comment by mdeweerd** [comment]
Cela m'intéresse de savoir s'ils activent 1 thread un mois renouvelable ou non renouvelable ( https://captchaai.com/orders.php ).

**Comment by mdeweerd** [comment]
Suite à une erreur de manip "git" lors d'un rebase, l'évolution pour captchaai est perdu.
L'offre n'étant valable qu'un mois, il n'est en plus pas assez intéresant pour ajouter cela à nouveau...

**Comment by lambd1** [comment]
exact, valable 1 mois ;)

**Comment by lambd1** [comment]
Tout fonctionne très bien pour moi avec 2captcha_token. Merci pour votre aide ;)
